### ISSUE TITLE
Error: could not find tiller

### ISSUE THREAD

**Issue by scavalier** [wunderio/silta-circleci#62]
Hello guys, 

Thanks for you incredible work.
I try to use you circleci to build my own project. All the CI works fine. but at the stet : helm-cleanup
I have an error.
Error: could not find tiller

Do you have an idea ?

**Comment by Jancis** [comment]
I might be a bit late with support, but it means the tiller is not set up on the cluster. Helm 2 required it, Helm 3 works without it.
Closing the issue now.
